Check if application starts

diff --git a/.github/workflows/deployment.yml b/.github/workflows/deployment.yml
--- a/.github/workflows/deployment.yml
+++ b/.github/workflows/deployment.yml
@@ -91,3 +91,11 @@ jobs:
           script: |
             cd /root/projects/api.maxkruiswegt.com/
             nohup java -jar api-0.0.1-SNAPSHOT.jar > output.log 2>&1 &
+            sleep 10 # Wait for the application to start
+            if pgrep -f 'java -jar api-0.0.1-SNAPSHOT.jar' > /dev/null; then
+              echo "Application started successfully."
+              exit 0
+            else
+              echo "Application failed to start."
+              exit 1
+            fi
